name = "tg-image-fetcher"
main = "src/index.ts"
compatibility_date = "2023-10-30"
node_compat = true

kv_namespaces = [
  { binding = "AVATAR_META", id = "41062a4d63c4486d9178710b5e28f0c5", preview_id = "41062a4d63c4486d9178710b5e28f0c5" }
]

[[queues.consumers]]
queue = "tg-image-fetcher"

[[queues.producers]]
queue = "tg-image-fetcher"
binding = "IMAGE_FETCH_QUEUE"

[[r2_buckets]]
binding = 'ASSETS_STORE'
bucket_name = 'crv-assets'
preview_bucket_name = 'crv-assets'

[placement]
mode = "smart"
